version: '3'

services:
  app:
    build: .
    image: laraveldocker
    container_name: laraveldocker
    restart: unless-stopped
    tty: true
    command: php-fpm
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/laraveldocker
    volumes:
      - .:/var/www/laraveldocker
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laraveldocker

  webserver:
    image: nginx:alpine
    container_name: nginxlaraveldocker
    restart: unless-stopped
    tty: true
    ports:
      - "2025:80"
    volumes:
      - .:/var/www/laraveldocker
      - ./storage/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laraveldocker

  db:
    image: mysql:5.7
    container_name: dblaraveldocker
    restart: always
    tty: true
    ports:
      - "20222:3306"
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldocker
      MYSQL_PASSWORD: laraveldocker
      MYSQL_ROOT_PASSWORD: laraveldocker
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laraveldocker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmalaraveldocker
    restart: always
    ports:
      - "7000:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - laraveldocker

  code-server:
    image: codercom/code-server:latest
    container_name: codeserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PASSWORD: "GPUYAHUD" # Ganti kalau perlu
    volumes:
      - .:/home/coder/project
    working_dir: /home/coder/project
    networks:
      - laraveldocker

networks:
  laraveldocker:
    driver: bridge

volumes:
  lbdata:
    driver: local
